# Generated by Django 6.0.5 on 2026-05-17 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del insumo')),
                ('unidad', models.CharField(choices=[('UNIDAD', 'Unidad'), ('KG', 'Kilogramo'), ('GR', 'Gramo'), ('LT', 'Litro'), ('ML', 'Mililitro')], max_length=20, verbose_name='Unidad de medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock minimo (alerta)')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo unitario (S/.)')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_porcion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad por porcion')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='inventario.insumo', verbose_name='Insumo')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='menu.plato', verbose_name='Plato')),
            ],
            options={
                'verbose_name': 'Receta de Insumo',
                'verbose_name_plural': 'Recetas de Insumos',
                'unique_together': {('plato', 'insumo')},
            },
        ),
    ]
