# Generated by Django 5.0.6 on 2026-05-20 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario (S/.)'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actual'),
        ),
    ]
