# Generated by Django 5.0.6 on 2026-05-22 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_insumo_costo_unitario_and_more'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEDUCCION', 'Deducción por comanda'), ('REPOSICION', 'Reposición por anulación'), ('AJUSTE', 'Ajuste manual'), ('COMPRA', 'Compra / Ingreso')], max_length=20, verbose_name='Tipo de movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (valor absoluto)')),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock antes del movimiento')),
                ('stock_posterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock después del movimiento')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de Insumo',
                'verbose_name_plural': 'Movimientos de Insumos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='insumo',
            constraint=models.CheckConstraint(check=models.Q(('stock_actual__gte', 0)), name='stock_no_negativo'),
        ),
        migrations.AddField(
            model_name='movimientoinsumo',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_insumo', to='pedidos.comanda', verbose_name='Comanda relacionada'),
        ),
        migrations.AddField(
            model_name='movimientoinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.insumo', verbose_name='Insumo'),
        ),
        migrations.AddField(
            model_name='movimientoinsumo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el movimiento'),
        ),
    ]
