# Generated by Django 5.0.6 on 2026-05-23 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinsumo_insumo_stock_no_negativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la receta')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='recetainsumo',
            options={'verbose_name': 'Insumo de Receta', 'verbose_name_plural': 'Insumos de Recetas'},
        ),
        migrations.AlterUniqueTogether(
            name='recetainsumo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recetainsumo',
            name='receta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='inventario.receta', verbose_name='Receta'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='recetainsumo',
            unique_together={('receta', 'insumo')},
        ),
        migrations.RemoveField(
            model_name='recetainsumo',
            name='plato',
        ),
    ]
