# Generated by Django 5.0.6 on 2026-05-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_receta_alter_recetainsumo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetainsumo',
            name='unidad',
            field=models.CharField(choices=[('UNIDAD', 'Unidad'), ('KG', 'Kilogramo'), ('GR', 'Gramo'), ('LT', 'Litro'), ('ML', 'Mililitro')], default='UNIDAD', max_length=20, verbose_name='Unidad en la receta'),
        ),
    ]
