# Generated by Django 5.0.6 on 2026-07-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_recetainsumo_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la unidad')),
                ('es_base', models.BooleanField(default=False, verbose_name='¿Es unidad base?')),
                ('contiene_cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad que contiene de la subunidad')),
                ('contiene_unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_padre', to='inventario.unidadconversion', verbose_name='Subunidad que contiene')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_conversion', to='inventario.insumo', verbose_name='Insumo asociado (solo si no es base)')),
            ],
            options={
                'verbose_name': 'Conversión de Unidad',
                'verbose_name_plural': 'Conversiones de Unidades',
                'unique_together': {('nombre', 'insumo')},
            },
        ),
    ]
