# Generated by Django 5.0.6 on 2026-07-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_insumo_activo_insumo_actualizado_en_insumo_creado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinsumo',
            name='origen',
            field=models.CharField(choices=[('COMANDA', 'Comanda'), ('COMPRA', 'Compra'), ('AJUSTE', 'Ajuste'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20, verbose_name='Origen del movimiento'),
        ),
    ]
