# Generated by Django 5.0.6 on 2026-07-18 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_movimientoinsumo_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la presentación')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad contenida')),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('KG', 'Kilogramo'), ('GR', 'Gramo'), ('LT', 'Litro'), ('ML', 'Mililitro')], max_length=20, verbose_name='Unidad de medida')),
                ('costo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de compra (S/)')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es presentación principal?')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='inventario.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Presentación de Insumo',
                'verbose_name_plural': 'Presentaciones de Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('equivalencia_cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad equivalente en unidad base')),
                ('equivalencia_unidad', models.CharField(choices=[('UNIDAD', 'Unidad'), ('KG', 'Kilogramo'), ('GR', 'Gramo'), ('LT', 'Litro'), ('ML', 'Mililitro')], max_length=20, verbose_name='Unidad base de equivalencia')),
                ('grupo', models.CharField(choices=[('VOLUMEN', 'Volumen'), ('PESO', 'Peso'), ('CANTIDAD', 'Cantidad')], default='VOLUMEN', max_length=20, verbose_name='Grupo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad de Cocina',
                'verbose_name_plural': 'Unidades de Cocina',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='recetainsumo',
            name='unidad_cocina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receta_insumos', to='inventario.unidadcocina', verbose_name='Unidad de cocina'),
        ),
    ]
