# Generated by Django 5.0.6 on 2026-07-18 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_presentacioninsumo_unidadcocina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacioninsumo',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='inventario.insumo', verbose_name='Insumo'),
        ),
    ]
