# Generated by Django 6.0.5 on 2026-05-17 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('mesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PREPARACION', 'En Preparacion'), ('LISTA', 'Lista'), ('COBRADA', 'Cobrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=20, verbose_name='Estado de la comanda')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='mesas.mesa', verbose_name='Mesa')),
                ('mozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mozo que atiende')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='LineaComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('observacion', models.TextField(blank=True, verbose_name='Observacion (ej: sin cebolla)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREP', 'En Preparacion'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20, verbose_name='Estado de preparacion')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pedidos.comanda', verbose_name='Comanda')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.plato', verbose_name='Plato')),
            ],
            options={
                'verbose_name': 'Linea de Comanda',
                'verbose_name_plural': 'Lineas de Comanda',
            },
        ),
        migrations.AddIndex(
            model_name='comanda',
            index=models.Index(fields=['mesa', 'estado'], name='pedidos_com_mesa_id_4f2e9b_idx'),
        ),
    ]
