from typing import Optional, Protocol, List
from dominio.entidades.comanda import Comanda
from dominio.entidades.mesa import Mesa
from dominio.entidades.reserva import Reserva
from dominio.entidades.plato import Plato
from dominio.entidades.insumo import Insumo
from dominio.entidades.caja import Caja
from dominio.entidades.linea_comanda import LineaComanda
from dominio.entidades.pago import Pago
from dominio.entidades.categoria import Categoria
from dominio.entidades.union_mesa import UnionMesa
from dominio.entidades.movimiento_insumo import MovimientoInsumo
from dominio.entidades.unidad_conversion import UnidadConversion
from dominio.entidades.receta import Receta
from dominio.entidades.receta_insumo import RecetaInsumo
from dominio.entidades.usuario import Usuario

class IComandaRepository(Protocol):
    def obtener_por_id(self, comanda_id: int) -> Optional[Comanda]: ...
    def obtener_con_bloqueo(self, comanda_id: int) -> Optional[Comanda]: ...
    def obtener_con_lineas(self, comanda_id: int) -> Optional[Comanda]: ...
    def guardar(self, comanda: Comanda) -> Comanda: ...
    def listar(self) -> List[Comanda]: ...
    def listar_activas(self) -> List[Comanda]: ...
    def listar_por_mesa(self, mesa_id: int) -> List[Comanda]: ...
    def listar_para_kds(self) -> List[Comanda]: ...
    def obtener_con_bloqueo(self, comanda_id: int) -> Optional[Comanda]: ...
    def listar_pendientes_por_caja(self, caja_id: int) -> List[Comanda]: ...
    def contar_activas(self) -> int: ...

class IMesaRepository(Protocol):
    def obtener_por_id(self, mesa_id: int) -> Optional[Mesa]: ...
    def obtener_con_bloqueo(self, mesa_id: int) -> Optional[Mesa]: ...
    def obtener_con_union(self, mesa_id: int) -> Optional[Mesa]: ...
    def guardar(self, mesa: Mesa) -> Mesa: ...
    def listar_activas(self) -> List[Mesa]: ...
    def listar_por_zona(self, zona: str) -> List[Mesa]: ...
    def listar_activas_por_ids(self, ids: List[int]) -> List[Mesa]: ...
    def obtener_con_bloqueo(self, mesa_id: int) -> Optional[Mesa]: ...

class IReservaRepository(Protocol):
    def obtener_por_id(self, reserva_id: int) -> Optional[Reserva]: ...
    def obtener_con_bloqueo(self, reserva_id: int) -> Optional[Reserva]: ...
    def guardar(self, reserva: Reserva) -> Reserva: ...
    def listar(self) -> List[Reserva]: ...
    def eliminar(self, reserva_id: int) -> None: ...
    def listar_activas_por_mesa(self, mesa_id: int) -> List[Reserva]: ...
    def listar_activas_por_union(self, union_id: int) -> List[Reserva]: ...
    def obtener_con_bloqueo(self, reserva_id: int) -> Optional[Reserva]: ...

class IPlatoRepository(Protocol):
    def obtener_por_id(self, plato_id: int) -> Optional[Plato]: ...
    def guardar(self, plato: Plato) -> Plato: ...
    def listar(self) -> List[Plato]: ...
    def listar_disponibles(self) -> List[Plato]: ...
    def listar_por_ids(self, ids: list) -> List[Plato]: ...
    def eliminar(self, plato_id: int) -> None: ...

class IInsumoRepository(Protocol):
    def obtener_por_id(self, insumo_id: int) -> Optional[Insumo]: ...
    def guardar(self, insumo: Insumo) -> Insumo: ...
    def listar(self) -> List[Insumo]: ...
    def listar_por_ids(self, ids: list[int]) -> List[Insumo]: ...
    def listar_criticos(self) -> List[Insumo]: ...
    def obtener_con_bloqueo(self, insumo_id: int) -> Optional[Insumo]: ...
    def eliminar(self, insumo_id: int) -> None: ...

class ICajaRepository(Protocol):
    def obtener_abierta(self) -> Optional[Caja]: ...
    def existe_abierta(self) -> bool: ...
    def guardar(self, caja: Caja) -> Caja: ...
    def listar(self) -> List[Caja]: ...

class IPagoRepository(Protocol):
    def obtener_por_id(self, pago_id: int) -> Optional[Pago]: ...
    def guardar(self, pago: Pago) -> Pago: ...
    def listar_por_comanda(self, comanda_id: int) -> List[Pago]: ...
    def listar_por_caja(self, caja_id: int) -> List[Pago]: ...
    def listar(self) -> List[Pago]: ...
    def total_por_caja(self, caja_id: int) -> float: ...
    def listar_por_rango_fecha(self, fecha_inicio, fecha_fin) -> List[Pago]: ...

class ILineaComandaRepository(Protocol):
    def obtener_por_id(self, linea_id: int) -> Optional[LineaComanda]: ...
    def guardar(self, linea: LineaComanda) -> LineaComanda: ...
    def guardar_lote(self, lineas: List[LineaComanda]) -> None: ...
    def obtener_con_bloqueo(self, linea_id: int) -> Optional[LineaComanda]: ...
    def listar(self) -> List[LineaComanda]: ...
    def listar_por_comanda(self, comanda_id: int) -> List[LineaComanda]: ...
    def guardar_lote(self, lineas: List[LineaComanda]) -> None: ...
    def cambiar_comanda_lote(self, comanda_origen_id: int, comanda_destino_id: int) -> None: ...
    def obtener_con_bloqueo(self, linea_id: int) -> Optional[LineaComanda]: ...

class ICategoriaRepository(Protocol):
    def obtener_por_id(self, categoria_id: int) -> Optional[Categoria]: ...
    def guardar(self, categoria: Categoria) -> Categoria: ...
    def listar(self) -> List[Categoria]: ...
    def listar_con_platos(self) -> List: ...

class IUnionMesaRepository(Protocol):
    def guardar(self, union: UnionMesa) -> UnionMesa: ...
    def obtener_por_id(self, union_id: int) -> Optional[UnionMesa]: ...
    def obtener_activa_por_mesa(self, mesa_id: int) -> Optional[UnionMesa]: ...
    def obtener_por_mesa(self, mesa_id: int) -> Optional[UnionMesa]: ...
    def listar_activas(self) -> List[UnionMesa]: ...

class IMovimientoInsumoRepository(Protocol):
    def guardar_lote(self, movimientos: List[MovimientoInsumo]) -> None: ...
    def guardar(self, movimiento: MovimientoInsumo) -> MovimientoInsumo: ...

class IUnidadConversionRepository(Protocol):
    def obtener_por_id(self, unidad_id: int) -> Optional[UnidadConversion]: ...
    def guardar(self, unidad: UnidadConversion) -> UnidadConversion: ...
    def listar(self) -> List[UnidadConversion]: ...

class IRecetaRepository(Protocol):
    def obtener_o_crear(self, nombre: str) -> Receta: ...
    def guardar(self, receta: Receta) -> Receta: ...
    def eliminar(self, receta_id: int) -> None: ...
    def listar(self) -> List[Receta]: ...
    def listar_receta_insumos(self) -> List[RecetaInsumo]: ...
    def obtener_receta_insumo(self, receta_insumo_id: int) -> Optional[RecetaInsumo]: ...
    def obtener_receta_insumo_o_crear(self, receta_id: int, insumo_id: int, cantidad: float, unidad: str) -> RecetaInsumo: ...
    def eliminar_receta_insumo(self, ri_id: int) -> None: ...
    def actualizar_receta_insumo(self, ri_id: int, **kwargs) -> RecetaInsumo: ...

class IUsuarioRepository(Protocol):
    def obtener_por_id(self, user_id: int) -> Optional[Usuario]: ...
    def listar(self) -> List[Usuario]: ...
    def crear(self, username: str, password: str, grupo_nombre: str = None, **extra) -> Usuario: ...
    def actualizar(self, user: Usuario) -> Usuario: ...
    def sincronizar_grupos(self, user_id: int, rol: str) -> None: ...
