from typing import Optional, Protocol, List
from dominio.entidades.comanda import Comanda
from dominio.entidades.mesa import Mesa
from dominio.entidades.reserva import Reserva
from dominio.entidades.plato import Plato
from dominio.entidades.insumo import Insumo
from dominio.entidades.caja import Caja
from dominio.entidades.linea_comanda import LineaComanda
from dominio.entidades.pago import Pago
from dominio.entidades.categoria import Categoria

class IComandaRepository(Protocol):
    def obtener_por_id(self, comanda_id: int) -> Optional[Comanda]: ...
    def guardar(self, comanda: Comanda) -> Comanda: ...
    def listar_activas(self) -> List[Comanda]: ...
    def listar_por_mesa(self, mesa_id: int) -> List[Comanda]: ...

class IMesaRepository(Protocol):
    def obtener_por_id(self, mesa_id: int) -> Optional[Mesa]: ...
    def guardar(self, mesa: Mesa) -> Mesa: ...
    def listar_activas(self) -> List[Mesa]: ...
    def listar_por_zona(self, zona: str) -> List[Mesa]: ...

class IReservaRepository(Protocol):
    def obtener_por_id(self, reserva_id: int) -> Optional[Reserva]: ...
    def guardar(self, reserva: Reserva) -> Reserva: ...
    def listar(self) -> List[Reserva]: ...
    def eliminar(self, reserva_id: int) -> None: ...

class IPlatoRepository(Protocol):
    def obtener_por_id(self, plato_id: int) -> Optional[Plato]: ...
    def guardar(self, plato: Plato) -> Plato: ...
    def listar_disponibles(self) -> List[Plato]: ...
    def eliminar(self, plato_id: int) -> None: ...

class IInsumoRepository(Protocol):
    def obtener_por_id(self, insumo_id: int) -> Optional[Insumo]: ...
    def guardar(self, insumo: Insumo) -> Insumo: ...
    def listar(self) -> List[Insumo]: ...
    def listar_criticos(self) -> List[Insumo]: ...

class ICajaRepository(Protocol):
    def obtener_abierta(self) -> Optional[Caja]: ...
    def guardar(self, caja: Caja) -> Caja: ...

class IPagoRepository(Protocol):
    def obtener_por_id(self, pago_id: int) -> Optional[Pago]: ...
    def guardar(self, pago: Pago) -> Pago: ...
    def listar_por_comanda(self, comanda_id: int) -> List[Pago]: ...

class ILineaComandaRepository(Protocol):
    def obtener_por_id(self, linea_id: int) -> Optional[LineaComanda]: ...
    def guardar(self, linea: LineaComanda) -> LineaComanda: ...
    def listar_por_comanda(self, comanda_id: int) -> List[LineaComanda]: ...

class ICategoriaRepository(Protocol):
    def obtener_por_id(self, categoria_id: int) -> Optional[Categoria]: ...
    def guardar(self, categoria: Categoria) -> Categoria: ...
    def listar(self) -> List[Categoria]: ...