# Generated by Django 6.0.5 on 2026-05-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Numero de mesa')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad maxima de personas')),
                ('zona', models.CharField(choices=[('SALON', 'Salon Principal'), ('TERRAZA', 'Terraza'), ('VIP', 'VIP')], default='SALON', max_length=20, verbose_name='Zona del salon')),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('LIMPIEZA', 'Limpieza')], default='LIBRE', max_length=20, verbose_name='Estado actual')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='UnionMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, verbose_name='¿La union esta activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('Mesa', models.ManyToManyField(related_name='uniones', to='mesas.mesa', verbose_name='Mesas que componen la union')),
            ],
            options={
                'verbose_name': 'Union de Mesas',
                'verbose_name_plural': 'Uniones de Mesas',
            },
        ),
    ]
