# Generated by Django 5.0.6 on 2026-05-19 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unionmesa',
            old_name='Mesa',
            new_name='mesas',
        ),
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad maxima de personas'),
        ),
    ]
