# Generated by Django 5.0.6 on 2026-05-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_rename_mesa_unionmesa_mesas_alter_mesa_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='¿Mesa activa?'),
        ),
    ]
