# Generated by Django 6.0.5 on 2026-05-17 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=50, verbose_name='Nombre del turno (ej: TARDE)')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo inicial (S/.)')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20, verbose_name='Estado del turno')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cajero responsable')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de credito/debito'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20, verbose_name='Metodo de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto recibido (S/.)')),
                ('vuelto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vuelto (S/.)')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia (ej: VISA ****1234)')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pago')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.comanda', verbose_name='Comanda')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
    ]
