# Generated by Django 5.0.6 on 2026-07-09 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_modelobase_actualizado_en'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeloBase',
        ),
    ]
