# Generated by Django 6.0.5 on 2026-05-17 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoria')),
                ('es_bebida', models.BooleanField(default=False, verbose_name='Es bebida?')),
                ('orden_display', models.IntegerField(default=0, verbose_name='Orden de visualizacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['orden_display'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del plato')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (S/.)')),
                ('tiempo_preparacion_min', models.IntegerField(default=15, verbose_name='Tiempo de preparacion (minutos)')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='platos/', verbose_name='Imagen del plato')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='menu.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'ordering': ['categoria__orden_display', 'nombre'],
            },
        ),
    ]
