# Generated by Django 5.0.6 on 2026-05-23 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_receta_alter_recetainsumo_options_and_more'),
        ('menu', '0002_alter_plato_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='receta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='platos', to='inventario.receta', verbose_name='Receta'),
            preserve_default=False,
        ),
    ]
