# Generated by Django 5.0.6 on 2026-05-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_union_mesa_alter_reserva_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
